# Generated by Django 5.0.6 on 2024-07-08 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('coordinate', models.TextField(blank=True, default='')),
                ('website', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='building_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('Building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite_Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Added', 'Добавлено'), ('Not_added', 'Не добавлено')], default='Not_added', max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='main.buildings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='building_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroupBuildings', to='main.groupbuildings'),
        ),
    ]
