# Generated by Django 5.0.6 on 2024-07-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='building_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='GroupBuildings', to='main.groupbuildings'),
        ),
    ]
