# Generated by Django 5.0.6 on 2024-07-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='nan', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
