# Generated by Django 5.0.6 on 2024-07-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_buildings_building_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='description',
        ),
    ]
