# Generated by Django 5.0.6 on 2024-07-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_buildings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuildings',
            name='base_style',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='groupbuildings',
            name='highlighted_style',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
