# Generated by Django 5.0.6 on 2024-07-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
    ]
